export {
    type DownloadStatus,
    type DownloadedEpisode,
    type DownloadedAnimeInfo,
    getDownloadEpisodeId,
    getAnimeInfo,
    isEpisodeDownloaded,
    getEpisodeDownloadStatus,
    getDownloadedEpisode,
    getDownloadedEpisodesForMedia,
    getCompletedEpisodesForMedia,
    getAllDownloadedAnime,
    getActiveDownloads,
    getFailedDownloads,
    getAnimeTotalDownloadSize,
    removeAllAnimeDownloadsForMedia,
} from "./download-store"

export {
    startEpisodeDownload,
    startBatchDownload,
    cancelAnimeDownload,
    clearAllAnimeDownloads,
    deleteAllAnimeDownloadsForMedia,
    deleteAnimeDownloadedFile,
    formatBytes,
    getAnimeDownloadDiskUsage,
    isAnimeDownloadActive,
    getAnimeActiveDownloadCount,
    resumeAnimeDownload,
    resumeStalledAnimeDownloads,
    retryAnimeDownload,
    retryFailedAnimeDownloads,
    isLocalServer,
} from "./download-manager"

export {
    useIsEpisodeDownloaded,
    useEpisodeDownloadStatus,
    useEpisodeDownloadInfo,
    useIsEpisodeDownloading,
    useDownloadedEpisodesForMedia,
    useCompletedEpisodesForMedia,
    useActiveAnimeDownloads,
    useFailedAnimeDownloads,
    useAllDownloadedAnime,
    useAnimeTotalDownloadSize,
    useAnimeDownloadDiskUsage,
    useStartEpisodeDownload,
    useStartAnimeBatchDownload,
    useCancelAnimeDownload,
    useDeleteAnimeDownload,
    useDeleteAnimeQueueItems,
    useDeleteAllAnimeDownloadsForMedia,
    useClearAllAnimeDownloads,
    useResumeAnimeDownload,
    useResumeAllAnimeDownloads,
    useRetryAnimeDownload,
    useRetryAllFailedAnimeDownloads,
    useIsLocalServer,
    useDownloadedEpisodeCount,
} from "./use-downloads"

export {
    type DownloadedMedia,
    downloadedAnimeMedia,
    downloadedMangaMedia,
} from "./downloaded-media"

////////////////////////// Manga chapter downloads

export {
    type DownloadedMangaChapter,
    type DownloadedMangaInfo,
    type MangaDownloadStatus,
    getMangaInfo,
    isMangaChapterDownloaded,
    getDownloadedMangaChapter,
    getDownloadedChaptersForMedia as getMangaDownloadedChaptersForMedia,
    getCompletedChaptersForMedia as getMangaCompletedChaptersForMedia,
    getAllDownloadedManga,
    getAllDownloadedChaptersForMediaAllProviders,
    getActiveMangaDownloads,
    getFailedMangaDownloads,
} from "./manga-download-store"

export {
    enqueueMangaChapterDownloads,
    cancelMangaChapterDownload,
    cancelAllMangaDownloads,
    deleteMangaChapterDownload,
    deleteAllMangaDownloadsForMedia as deleteAllMangaDownloads,
    clearAllMangaDownloads,
    getLocalChapterPages,
    getMangaDownloadQueueLength,
    isMangaChapterActive,
    isMangaChapterDownloading,
    getMangaDownloadDiskUsage,
    resumeMangaChapterDownload,
    resumeStalledMangaDownloads,
    retryMangaChapterDownload,
    retryFailedMangaDownloads,
} from "./manga-download-manager"

export {
    useIsMangaChapterDownloaded,
    useMangaChapterDownloadInfo,
    useMangaChapterDownloadStatus,
    useIsMangaChapterDownloading,
    useDownloadedMangaChapters,
    useCompletedMangaChapters,
    useAllDownloadedMangaChapters,
    useAllDownloadedManga,
    useMangaDownloadQueueLength,
    useMangaDownloadDiskUsage,
    useStartMangaChapterDownload,
    useCancelMangaChapterDownload,
    useDeleteMangaChapterDownload,
    useDeleteMangaQueueItems,
    useDeleteAllMangaDownloadsForMedia,
    useClearAllMangaDownloads,
    useLocalMangaChapterPages,
    useActiveMangaDownloads,
    useFailedMangaDownloads,
    useResumeMangaChapterDownload,
    useResumeAllMangaDownloads,
    useRetryMangaChapterDownload,
    useRetryAllFailedMangaDownloads,
} from "./use-manga-downloads"
